# Generated by Django 5.0.7 on 2024-08-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('logged_in', 'Logged In'), ('logged_out', 'Logged Out')], max_length=20),
        ),
    ]
