# Generated by Django 5.1.4 on 2025-01-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_deliverypersonnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('expert_id', models.AutoField(primary_key=True, serialize=False)),
                ('expertise_area', models.CharField(max_length=255)),
                ('qualifications', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='expert_profiles/')),
                ('specialization_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('availability_schedule', models.JSONField(blank=True, null=True)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('consultation_count', models.IntegerField(default=0)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(default=0)),
                ('blog_count', models.IntegerField(default=0)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('date_time_joined', models.DateTimeField(auto_now_add=True)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userauths.login')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userauths.user_reg')),
            ],
        ),
    ]
