# Generated by Django 5.1.4 on 2025-01-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_expert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverypersonnel',
            options={'verbose_name': 'Delivery Personnel', 'verbose_name_plural': 'Delivery Personnel'},
        ),
        migrations.RemoveField(
            model_name='deliverypersonnel',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='deliverypersonnel',
            name='login',
        ),
        migrations.AddField(
            model_name='deliverypersonnel',
            name='area_of_delivery',
            field=models.CharField(choices=[('kottayam', 'Kottayam'), ('pathanamthitta', 'Pathanamthitta'), ('idukki', 'Idukki'), ('thodupuzha', 'Thodupuzha'), ('ernakulam', 'Ernakulam')], default='Not Assigned', max_length=255),
        ),
        migrations.AddField(
            model_name='deliverypersonnel',
            name='completed_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverypersonnel',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverypersonnel',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverypersonnel',
            name='assigned_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
