# Generated by Django 5.1.4 on 2025-01-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_deliverypersonnel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverypersonnel',
            old_name='delivery_person_id',
            new_name='delivery_id',
        ),
    ]
