# Generated by Django 5.1.4 on 2025-01-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_rename_delivery_person_id_deliverypersonnel_delivery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypersonnel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='expert_profiles/'),
        ),
    ]
