# Generated by Django 5.1.2 on 2025-02-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_deliverypersonnel_daily_order_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypersonnel',
            name='area_of_delivery',
            field=models.CharField(choices=[('kottayam', 'Kottayam'), ('pathanamthitta', 'Pathanamthitta'), ('idukki', 'Idukki'), ('thodupuzha', 'Thodupuzha'), ('ernakulam', 'Ernakulam')], max_length=50),
        ),
    ]
