# Generated by Django 5.1.2 on 2025-02-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_alter_deliverypersonnel_area_of_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypersonnel',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='deliverypersonnel',
            name='current_longitude',
        ),
    ]
