# Generated by Django 5.1.2 on 2025-02-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0012_remove_deliverypersonnel_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypersonnel',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverypersonnel',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverypersonnel',
            name='area_of_delivery',
            field=models.CharField(choices=[('kottayam', 'Kottayam'), ('pathanamthitta', 'Pathanamthitta'), ('idukki', 'Idukki'), ('thodupuzha', 'Thodupuzha'), ('ernakulam', 'Ernakulam')], default='Not Assigned', max_length=255),
        ),
    ]
