# Generated by Django 5.1.2 on 2025-02-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0015_expert_phone_enabled_alter_expert_session_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='availability_schedule',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {\n            'monday': {'start': '09:00', 'end': '17:00', 'available': true},\n            'tuesday': {'start': '09:00', 'end': '17:00', 'available': true},\n            ...\n        }", null=True),
        ),
    ]
