# Generated by Django 5.1.2 on 2025-03-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0016_alter_expert_availability_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='chat_enabled',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='meet_link',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='phone_enabled',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='session_duration',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='session_price',
        ),
        migrations.AlterField(
            model_name='expert',
            name='availability_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
