# Generated by Django 5.1.7 on 2025-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0017_remove_expert_chat_enabled_remove_expert_meet_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='chat_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='phone_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='session_duration',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='expert',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expert',
            name='availability_schedule',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {\n            'monday': {'start': '09:00', 'end': '17:00', 'available': true},\n            'tuesday': {'start': '09:00', 'end': '17:00', 'available': true},\n            ...\n        }", null=True),
        ),
    ]
