# Generated by Django 5.1.2 on 2025-02-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_QA_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertsession',
            options={'ordering': ['-session_date']},
        ),
        migrations.RemoveField(
            model_name='expertsession',
            name='call_id',
        ),
        migrations.RemoveField(
            model_name='expertsession',
            name='session_link',
        ),
        migrations.RemoveField(
            model_name='expertsession',
            name='session_status',
        ),
        migrations.AlterField(
            model_name='expertsession',
            name='session_type',
            field=models.CharField(choices=[('chat', 'Chat Session'), ('phone', 'Phone Call'), ('video', 'Video Call')], max_length=10),
        ),
    ]
