# Generated by Django 5.1.4 on 2025-01-28 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_sessions', '0001_initial'),
        ('userauths', '0009_deliverypersonnel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnasession',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sessions', to='userauths.user_reg'),
        ),
        migrations.AlterField(
            model_name='qnasession',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_sessions', to='userauths.user_reg'),
        ),
    ]
