# Generated by Django 5.1.4 on 2025-01-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_sessions', '0002_alter_qnasession_admin_alter_qnasession_expert'),
        ('userauths', '0009_deliverypersonnel_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qnasession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='qnasession',
            name='admin',
        ),
        migrations.AddField(
            model_name='qnasession',
            name='current_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qnasession',
            name='customers',
            field=models.ManyToManyField(related_name='customer_sessions', to='userauths.user_reg'),
        ),
        migrations.AddField(
            model_name='qnasession',
            name='max_participants',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='qnasession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='qnasession',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_sessions', to='userauths.expert'),
        ),
    ]
