# Generated by Django 5.1 on 2024-10-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_responded',
            field=models.BooleanField(default=False, help_text='Indicates if a response has been sent'),
        ),
    ]
