# Generated by Django 5.1.2 on 2024-12-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_wishlist_email'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order', 'product'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The batch of the product, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.batch'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Discount percentage applied to this item.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='The order to which this item belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='purchase.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit at the time of order.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The product being purchased.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='The quantity of the product ordered.'),
        ),
    ]
