# Generated by Django 5.1.2 on 2024-12-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_order_billing'),
        ('purchase', '0004_alter_orderitem_product'),
        ('purchase', '0004_cart_is_completed'),
        ('purchase', '0007_alter_orderitem_discount'),
    ]

    operations = [
    ]
