# Generated by Django 5.1.2 on 2025-02-14 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauths', '0016_alter_expert_availability_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='plant_icons/')),
                ('model_3d', models.FileField(help_text='3D model file (.glb or .gltf)', upload_to='plant_models/')),
                ('min_spacing', models.FloatField(help_text='Minimum spacing between plants in meters')),
                ('height', models.FloatField(help_text='Average height of the plant in meters')),
            ],
        ),
        migrations.CreateModel(
            name='FieldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='field_images/')),
                ('width', models.FloatField(default=10.0, help_text='Field width in meters')),
                ('length', models.FloatField(default=10.0, help_text='Field length in meters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauths.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlantSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('rotation', models.FloatField(default=0)),
                ('is_ai_placed', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_garden.fieldimage')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_garden.planttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauths.user_reg')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('field', 'x_position', 'y_position'), name='unique_plant_position')],
            },
        ),
    ]
