# Generated by Django 5.1.4 on 2025-01-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_is_featured_blogpost_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='status',
        ),
    ]
