# Generated by Django 5.1.4 on 2025-01-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='deleted_at',
        ),
    ]
