# Generated by Django 5.1.2 on 2025-02-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_layout', '0002_alter_userlayout_plant_positions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlayout',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='userlayout',
            name='plot_length',
            field=models.FloatField(default=10.0, help_text='Length in meters'),
        ),
        migrations.AddField(
            model_name='userlayout',
            name='plot_width',
            field=models.FloatField(default=10.0, help_text='Width in meters'),
        ),
    ]
