# Generated by Django 5.1.2 on 2025-02-24 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_layout', '0003_alter_userlayout_options_userlayout_plot_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlayout',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='userlayout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userlayout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
