"""
<<<<<<< HEAD
Django settings for Enchanted_Eden project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
=======
Django settings for PlantNursery project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
>>>>>>> origin/main

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

<<<<<<< HEAD
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_&b(9(a%^7)t%%&9ctl$)bb8t2mo1djy8#kc_szj7ss6v!ahpk'
=======

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pee90+f#7do^v&%wl9g645og3r@d7k_ur)m1jzh4f0@l%w3h-7'
>>>>>>> origin/main

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

<<<<<<< HEAD
# Application definition

INSTALLED_APPS = [
    # 'jazzmin',  # Uncomment if you want to use jazzmin and ensure it's installed
=======

# Application definition

INSTALLED_APPS = [
    'jazzmin',
>>>>>>> origin/main
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'core',
    'userauths',
    'products',
=======

    'django.contrib.sites',
    
    

    # Custom Apps
    'core',
    'userauths',
>>>>>>> origin/main
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
<<<<<<< HEAD
=======
    'django.middleware.csrf.CsrfViewMiddleware',
>>>>>>> origin/main
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
<<<<<<< HEAD

ROOT_URLCONF = 'PlantNursery.urls'

=======
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Default, stores session data in the database

# Other session settings
SESSION_COOKIE_NAME = 'sessionid'  # Name of the session cookie
SESSION_COOKIE_AGE = 1209600  # 2 weeks, session expiration in seconds
SESSION_SAVE_EVERY_REQUEST = False  # Save the session to the database on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Whether to expire the session when the user closes their browser

ROOT_URLCONF = 'PlantNursery.urls'
>>>>>>> origin/main
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
<<<<<<< HEAD
=======
                'userauths.context_processors.site_context',  # Added this line
                'userauths.context_processors.site_info',      # Added this line
>>>>>>> origin/main
            ],
        },
    },
]

<<<<<<< HEAD
WSGI_APPLICATION = 'PlantNursery.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
=======

WSGI_APPLICATION = 'PlantNursery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
>>>>>>> origin/main

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
<<<<<<< HEAD
        'NAME': 'Enchanted_Eden',        # Replace with your database name
        'USER': 'postgres',        # Replace with your database user
        'PASSWORD': 'Amalda@123', # Replace with your database password
=======
        'NAME': 'PN',        # Replace with your database name
        'USER': 'postgres',        # Replace with your database user
        'PASSWORD': 'Amalda@123',# Replace with your database password
>>>>>>> origin/main
        'HOST': 'localhost',                 # Set to your database server's address
        'PORT': '5432',                      # Default PostgreSQL port
    }
}

<<<<<<< HEAD
# Session settings

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Default, stores session data in the database
SESSION_COOKIE_NAME = 'sessionid'  # Name of the session cookie
SESSION_COOKIE_AGE = 1209600  # 2 weeks, session expiration in seconds
SESSION_SAVE_EVERY_REQUEST = False  # Save the session to the database on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Whether to expire the session when the user closes their browser

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
=======
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
AUTH_USER_MODEL = 'userauths.User'  # Adjust 'userauths' to your app name if different


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
>>>>>>> origin/main

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

<<<<<<< HEAD
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
=======

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
>>>>>>> origin/main

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

<<<<<<< HEAD
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Site configuration
SITE_ID = 1
=======

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
STATICFILES_DIRS =[os.path.join(BASE_DIR,'static')]
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,"media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# PlantNursery/settings.py

JAZZMIN_SETTINGS = {
    'site_header': "Enchanted Eden",
    'site_brand': 'You order, we deliver',
    'site_logo': '/images/logo1.jpg',
    'copyright': 'enchanted-eden.com',
}

# settings.py

# Site Configuration
SITE_ID = 1 
>>>>>>> origin/main
SITE_NAME = 'Enchanted Eden'
DOMAIN = 'localhost:8000'
PASSWORD_RESET_EMAIL_TEMPLATE = 'userauths/password_reset_email.html'

# Email Backend Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'amaldapatrick2025@mca.ajce.in'
EMAIL_HOST_PASSWORD = 'Amalda@MCA'  # Consider using environment variables for security

DEFAULT_FROM_EMAIL = 'amaldapatrick2025@mca.ajce.in'

<<<<<<< HEAD
# Handle media uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
=======

# Email Backend Configuration

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


LOGIN_URL = '/user/login/'
>>>>>>> origin/main
