<<<<<<< HEAD
# Generated by Django 5.1 on 2024-09-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('sunlight_requirement', models.CharField(choices=[('Full Sun', 'Full Sun'), ('Partial Shade', 'Partial Shade'), ('Full Shade', 'Full Shade')], max_length=20)),
                ('water_need', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('climate_compatibility', models.CharField(choices=[('Tropical', 'Tropical'), ('Subtropical', 'Subtropical'), ('Temperate', 'Temperate'), ('Arid', 'Arid')], max_length=15)),
                ('growth_rate', models.CharField(choices=[('Slow', 'Slow'), ('Moderate', 'Moderate'), ('Fast', 'Fast')], max_length=10)),
                ('soil_type', models.CharField(choices=[('Sandy', 'Sandy'), ('Loamy', 'Loamy'), ('Clay', 'Clay'), ('Peaty', 'Peaty'), ('Silty', 'Silty')], max_length=10)),
                ('flowering_season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=10)),
                ('height_range', models.CharField(choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Tall', 'Tall')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
=======
# Generated by Django 5.1 on 2024-09-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('sunlight_requirement', models.CharField(choices=[('Full Sun', 'Full Sun'), ('Partial Shade', 'Partial Shade'), ('Full Shade', 'Full Shade')], max_length=20)),
                ('water_need', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('climate_compatibility', models.CharField(choices=[('Tropical', 'Tropical'), ('Subtropical', 'Subtropical'), ('Temperate', 'Temperate'), ('Arid', 'Arid')], max_length=15)),
                ('growth_rate', models.CharField(choices=[('Slow', 'Slow'), ('Moderate', 'Moderate'), ('Fast', 'Fast')], max_length=10)),
                ('soil_type', models.CharField(choices=[('Sandy', 'Sandy'), ('Loamy', 'Loamy'), ('Clay', 'Clay'), ('Peaty', 'Peaty'), ('Silty', 'Silty')], max_length=10)),
                ('flowering_season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=10)),
                ('height_range', models.CharField(choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Tall', 'Tall')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
>>>>>>> origin/main
