<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-10-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_plant', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Plant Types',
            },
        ),
        migrations.CreateModel(
            name='NonPlantProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('product_type', models.CharField(choices=[('plant', 'Plants'), ('tool', 'Tools'), ('fertilizer', 'Fertilizers'), ('pesticide', 'Pesticides')], max_length=50)),
                ('is_organic', models.BooleanField(default=False)),
                ('usage', models.TextField()),
                ('suitable_for_plants', models.TextField()),
                ('image_1', models.ImageField(upload_to='non_plant_products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='non_plant_products/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='non_plant_products/')),
                ('status', models.BooleanField(default=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Non-Plant Products',
            },
        ),
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.planttype')),
            ],
            options={
                'verbose_name_plural': 'Plant Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sunlight_requirement', models.CharField(choices=[('full_sun', 'Full Sun (6+ hours of direct sunlight)'), ('partial_sun', 'Partial Sun (4-6 hours of direct sunlight)'), ('partial_shade', 'Partial Shade (2-4 hours of direct sunlight)'), ('full_shade', 'Full Shade (less than 2 hours of direct sunlight)')], max_length=50)),
                ('water_requirement', models.CharField(choices=[('low', 'Low (water every 1-2 weeks)'), ('medium', 'Medium (water weekly)'), ('high', 'High (water multiple times a week)')], max_length=50)),
                ('soil_type', models.CharField(choices=[('loamy', 'Loamy (well-draining, nutrient-rich)'), ('sandy', 'Sandy (well-draining but nutrient-poor)'), ('clay', 'Clay (holds moisture but can be compacted)'), ('peat', 'Peat (rich in organic matter, retains moisture)'), ('silt', 'Silt (holds moisture and nutrients well)')], max_length=50)),
                ('growth_rate', models.CharField(choices=[('slow', 'Slow (takes longer to mature)'), ('medium', 'Medium (average growth rate)'), ('fast', 'Fast (grows quickly)')], max_length=50)),
                ('climate_suitability', models.CharField(choices=[('tropical', 'Tropical (suitable for hot and humid conditions)'), ('subtropical', 'Subtropical (suitable for warm conditions with cooler winters)'), ('temperate', 'Temperate (suitable for moderate temperatures)')], max_length=100)),
                ('image_1', models.ImageField(upload_to='products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('plant_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.plantcategory')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='CultivationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('steps', models.TextField()),
                ('recommended_tools', models.TextField(blank=True, null=True)),
                ('watering_frequency', models.CharField(max_length=50)),
                ('fertilization_guidelines', models.TextField(blank=True, null=True)),
                ('common_issues', models.TextField(blank=True, null=True)),
                ('basic_details', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Cultivation Methods',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('current_height', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
=======
# Generated by Django 5.0.7 on 2024-10-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_plant', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Plant Types',
            },
        ),
        migrations.CreateModel(
            name='NonPlantProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('product_type', models.CharField(choices=[('plant', 'Plants'), ('tool', 'Tools'), ('fertilizer', 'Fertilizers'), ('pesticide', 'Pesticides')], max_length=50)),
                ('is_organic', models.BooleanField(default=False)),
                ('usage', models.TextField()),
                ('suitable_for_plants', models.TextField()),
                ('image_1', models.ImageField(upload_to='non_plant_products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='non_plant_products/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='non_plant_products/')),
                ('status', models.BooleanField(default=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Non-Plant Products',
            },
        ),
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.planttype')),
            ],
            options={
                'verbose_name_plural': 'Plant Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sunlight_requirement', models.CharField(choices=[('full_sun', 'Full Sun (6+ hours of direct sunlight)'), ('partial_sun', 'Partial Sun (4-6 hours of direct sunlight)'), ('partial_shade', 'Partial Shade (2-4 hours of direct sunlight)'), ('full_shade', 'Full Shade (less than 2 hours of direct sunlight)')], max_length=50)),
                ('water_requirement', models.CharField(choices=[('low', 'Low (water every 1-2 weeks)'), ('medium', 'Medium (water weekly)'), ('high', 'High (water multiple times a week)')], max_length=50)),
                ('soil_type', models.CharField(choices=[('loamy', 'Loamy (well-draining, nutrient-rich)'), ('sandy', 'Sandy (well-draining but nutrient-poor)'), ('clay', 'Clay (holds moisture but can be compacted)'), ('peat', 'Peat (rich in organic matter, retains moisture)'), ('silt', 'Silt (holds moisture and nutrients well)')], max_length=50)),
                ('growth_rate', models.CharField(choices=[('slow', 'Slow (takes longer to mature)'), ('medium', 'Medium (average growth rate)'), ('fast', 'Fast (grows quickly)')], max_length=50)),
                ('climate_suitability', models.CharField(choices=[('tropical', 'Tropical (suitable for hot and humid conditions)'), ('subtropical', 'Subtropical (suitable for warm conditions with cooler winters)'), ('temperate', 'Temperate (suitable for moderate temperatures)')], max_length=100)),
                ('image_1', models.ImageField(upload_to='products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('plant_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.plantcategory')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='CultivationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('steps', models.TextField()),
                ('recommended_tools', models.TextField(blank=True, null=True)),
                ('watering_frequency', models.CharField(max_length=50)),
                ('fertilization_guidelines', models.TextField(blank=True, null=True)),
                ('common_issues', models.TextField(blank=True, null=True)),
                ('basic_details', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Cultivation Methods',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('current_height', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
>>>>>>> 1f7ed6f7831d74d3de04e0424065c63794fd8d85
