<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-10-11 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nonplantproduct',
            options={},
        ),
        migrations.RemoveField(
            model_name='cultivationmethod',
            name='basic_details',
        ),
        migrations.RemoveField(
            model_name='nonplantproduct',
            name='product_type',
        ),
        migrations.AddField(
            model_name='cultivationmethod',
            name='distance_between_plants',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Distance between plants in meters', max_digits=5),
        ),
        migrations.AddField(
            model_name='cultivationmethod',
            name='pit_size_height',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Height of the pit in meters', max_digits=5),
        ),
        migrations.AddField(
            model_name='cultivationmethod',
            name='pit_size_width',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Height of the pit in meters', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='best_time_to_plant',
            field=models.CharField(blank=True, choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.BooleanField(default=True, help_text='Set to active or inactive.'),
        ),
        migrations.AlterField(
            model_name='cultivationmethod',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivation_methods', to='products.product'),
        ),
        migrations.AlterField(
            model_name='cultivationmethod',
            name='status',
            field=models.BooleanField(default=True, help_text='Set to active or inactive.'),
        ),
        migrations.AlterField(
            model_name='nonplantproduct',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_plant': False}, on_delete=django.db.models.deletion.CASCADE, related_name='non_plant_products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='plantcategory',
            name='plant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.planttype'),
        ),
        migrations.AlterField(
            model_name='plantcategory',
            name='status',
            field=models.BooleanField(default=True, help_text='Set to active or inactive.'),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='status',
            field=models.BooleanField(default=True, help_text='Set to active or inactive.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='climate_suitability',
            field=models.CharField(choices=[('tropical', 'Tropical (hot and humid conditions)'), ('subtropical', 'Subtropical (warm with cooler winters)'), ('temperate', 'Temperate (moderate temperatures)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='growth_rate',
            field=models.CharField(choices=[('slow', 'Slow (takes longer to mature)'), ('medium', 'Medium (average growth rate)'), ('fast', 'Fast (grows quickly)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='soil_type',
            field=models.CharField(choices=[('loamy', 'Loamy (well-draining, nutrient-rich)'), ('sandy', 'Sandy (well-draining but nutrient-poor)'), ('clay', 'Clay (holds moisture but can be compacted)'), ('peat', 'Peat (rich in organic matter, retains moisture)'), ('silt', 'Silt (holds moisture and nutrients well)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, help_text='Set to active or inactive.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sunlight_requirement',
            field=models.CharField(choices=[('full_sun', 'Full Sun (6+ hours of direct sunlight)'), ('partial_sun', 'Partial Sun (4-6 hours of direct sunlight)'), ('partial_shade', 'Partial Shade (2-4 hours of direct sunlight)'), ('full_shade', 'Full Shade (less than 2 hours of direct sunlight)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='water_requirement',
            field=models.CharField(choices=[('low', 'Low (water every 1-2 weeks)'), ('medium', 'Medium (water weekly)'), ('high', 'High (water multiple times a week)')], max_length=20),
        ),
    ]
=======
# Generated by Django 5.0.7 on 2024-10-11 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nonplantproduct',
            options={},
        ),
        migrations.RemoveField(
            model_name='cultivationmethod',
            name='basic_details',
        ),
        migrations.RemoveField(
            model_name='nonplantproduct',
            name='product_type',
        ),
        migrations.AddField(
            model_name='cultivationmethod',
            name='distance_between_plants',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Distance between plants in meters', max_digits=5),
        ),
        migrations.AddField(
            model_name='cultivationmethod',
            name='pit_size_height',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Height of the pit in meters', max_digits=5),
        ),
        migrations.AddField(
            model_name='cultivationmethod',
            name='pit_size_width',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Height of the pit in meters', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='best_time_to_plant',
            field=models.CharField(blank=True, choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.BooleanField(default=True, help_text='Set to active or inactive.'),
        ),
        migrations.AlterField(
            model_name='cultivationmethod',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivation_methods', to='products.product'),
        ),
        migrations.AlterField(
            model_name='cultivationmethod',
            name='status',
            field=models.BooleanField(default=True, help_text='Set to active or inactive.'),
        ),
        migrations.AlterField(
            model_name='nonplantproduct',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_plant': False}, on_delete=django.db.models.deletion.CASCADE, related_name='non_plant_products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='plantcategory',
            name='plant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.planttype'),
        ),
        migrations.AlterField(
            model_name='plantcategory',
            name='status',
            field=models.BooleanField(default=True, help_text='Set to active or inactive.'),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='status',
            field=models.BooleanField(default=True, help_text='Set to active or inactive.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='climate_suitability',
            field=models.CharField(choices=[('tropical', 'Tropical (hot and humid conditions)'), ('subtropical', 'Subtropical (warm with cooler winters)'), ('temperate', 'Temperate (moderate temperatures)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='growth_rate',
            field=models.CharField(choices=[('slow', 'Slow (takes longer to mature)'), ('medium', 'Medium (average growth rate)'), ('fast', 'Fast (grows quickly)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='soil_type',
            field=models.CharField(choices=[('loamy', 'Loamy (well-draining, nutrient-rich)'), ('sandy', 'Sandy (well-draining but nutrient-poor)'), ('clay', 'Clay (holds moisture but can be compacted)'), ('peat', 'Peat (rich in organic matter, retains moisture)'), ('silt', 'Silt (holds moisture and nutrients well)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, help_text='Set to active or inactive.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sunlight_requirement',
            field=models.CharField(choices=[('full_sun', 'Full Sun (6+ hours of direct sunlight)'), ('partial_sun', 'Partial Sun (4-6 hours of direct sunlight)'), ('partial_shade', 'Partial Shade (2-4 hours of direct sunlight)'), ('full_shade', 'Full Shade (less than 2 hours of direct sunlight)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='water_requirement',
            field=models.CharField(choices=[('low', 'Low (water every 1-2 weeks)'), ('medium', 'Medium (water weekly)'), ('high', 'High (water multiple times a week)')], max_length=20),
        ),
    ]
>>>>>>> 1f7ed6f7831d74d3de04e0424065c63794fd8d85
