<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-10-11 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_planttype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttype',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_plant': True}, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
=======
# Generated by Django 5.0.7 on 2024-10-11 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_planttype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttype',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_plant': True}, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
>>>>>>> 1f7ed6f7831d74d3de04e0424065c63794fd8d85
