<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-10-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_category_product_plant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Plant_Type',
        ),
    ]
=======
# Generated by Django 5.0.7 on 2024-10-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_category_product_plant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Plant_Type',
        ),
    ]
>>>>>>> 1f7ed6f7831d74d3de04e0424065c63794fd8d85
