# Generated by Django 5.0.7 on 2024-10-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_category_product_plant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Plant_Type',
        ),
    ]
