# Generated by Django 5.0.7 on 2024-10-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_plant_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivationmethod',
            old_name='description',
            new_name='desc',
        ),
    ]
