<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-10-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_nonplantproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcategory',
            name='climate_suitability',
            field=models.CharField(blank=True, choices=[('tropical', 'Tropical (hot and humid conditions)'), ('subtropical', 'Subtropical (warm with cooler winters)'), ('temperate', 'Temperate (moderate temperatures)')], max_length=20, null=True),
        ),
    ]
=======
# Generated by Django 5.0.7 on 2024-10-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_nonplantproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcategory',
            name='climate_suitability',
            field=models.CharField(blank=True, choices=[('tropical', 'Tropical (hot and humid conditions)'), ('subtropical', 'Subtropical (warm with cooler winters)'), ('temperate', 'Temperate (moderate temperatures)')], max_length=20, null=True),
        ),
    ]
>>>>>>> 1f7ed6f7831d74d3de04e0424065c63794fd8d85
