# Generated by Django 5.0.7 on 2024-10-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_plantcategory_climate_suitability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
