<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-10-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_plantcategory_pot_soil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcategory',
            name='plant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.planttype'),
        ),
    ]
=======
# Generated by Django 5.0.7 on 2024-10-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_plantcategory_pot_soil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcategory',
            name='plant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.planttype'),
        ),
    ]
>>>>>>> 1f7ed6f7831d74d3de04e0424065c63794fd8d85
