# Generated by Django 5.0.7 on 2024-10-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_plantcategory_plant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcategory',
            name='plant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.planttype'),
        ),
    ]
