# Generated by Django 5.0.7 on 2024-10-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_plantcategory_plant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='size',
        ),
    ]
