<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-10-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_plantcategory_plant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='size',
        ),
    ]
=======
# Generated by Django 5.0.7 on 2024-10-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_plantcategory_plant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='size',
        ),
    ]
>>>>>>> 1f7ed6f7831d74d3de04e0424065c63794fd8d85
