# Generated by Django 5.0.7 on 2024-10-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_batch_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='no_of_plants',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
