<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-10-13 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_batch_no_of_plants'),
        ('userauths', '0002_login_login_count_user_reg_status_alter_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='The product that is added to the wishlist.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='products.product')),
                ('user_email', models.ForeignKey(help_text='The user who added the product to the wishlist.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='userauths.login', to_field='email')),
            ],
            options={
                'verbose_name_plural': 'Wishlists',
                'unique_together': {('user_email', 'product')},
            },
        ),
    ]
=======
# Generated by Django 5.0.7 on 2024-10-13 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_batch_no_of_plants'),
        ('userauths', '0002_login_login_count_user_reg_status_alter_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='The product that is added to the wishlist.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='products.product')),
                ('user_email', models.ForeignKey(help_text='The user who added the product to the wishlist.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='userauths.login', to_field='email')),
            ],
            options={
                'verbose_name_plural': 'Wishlists',
                'unique_together': {('user_email', 'product')},
            },
        ),
    ]
>>>>>>> 1f7ed6f7831d74d3de04e0424065c63794fd8d85
