# Generated by Django 5.0.7 on 2024-10-13 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_wishlist_options_and_more'),
        ('userauths', '0002_login_login_count_user_reg_status_alter_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauths.login'),
        ),
    ]
