# Generated by Django 5.1.4 on 2024-12-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
